version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    #command: "./dev_start.sh"
    restart: on-failure
    #privileged: yes
    ports:
      - "9041:5000"
    volumes:
      - ./api:/app
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /ziv/shared/bio_gpt:/ziv/shared/bio_gpt
    environment:
      - DEPLOYMENT=prod
      - GITEA_TOKEN=2b95404977c519bb5c6bf7e17842a77cff75919a
    env_file:
      - .env
      - .env.db
    depends_on:
      - rabbitmq
    networks:
      - api

  rabbitmq:
    image: rabbitmq:3-management
    hostname: duri_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    expose:
      - "5672"
      - "15672"
    ports:
      - "15673:15672"
    networks:
      - api

  redis:
    image: "redis/redis-stack:latest"
    hostname: redis
    ports:
      - "18001:8001"
    networks:
      - api

networks:
  api: {}
