version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    #command: "./dev_start.sh"
    restart: on-failure
    privileged: yes
    ports:
      - "9041:5000"
    volumes:
      - ./api:/app
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    environment:
      - DEPLOYMENT=prod
    env_file:
      - .env
      - .env.db
    depends_on:
      - rabbitmq
    networks:
      - intranet
      - api

  rabbitmq:
    image: rabbitmq:3-management
    hostname: duri_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    expose:
      - "5672"
      - "15672"
    ports:
      - "15673:15672"
    networks:
      - api

networks:
  intranet: {}
  api: {}
