version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    #command: "./dev_start.sh"
    restart: on-failure
    privileged: yes
    ports:
      - "9041:5000"
    volumes:
      - ./api:/app
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    env_file:
      - .env
      - .env.db
    networks:
      - intranet

networks:
  intranet: {}